### ISSUE TITLE
pidoc/core: Security vulnerability in markdown-it

### ISSUE THREAD

**Issue by sbley** [smapiot/pidoc#13]
Black Duck reports a security vulnerability in markdown-it 12.3.2 which is used in our project, matching the version identifier for markdown-it in pidoc/core, [^12.0.6](https://github.com/smapiot/pidoc/blob/develop/packages/core/package.json#L55).
It is reported to be fixed with markdown-it 13.0.2.
Could you please update the dependencies accordingly?

pidoc/core 0.18.0
CWE-400, CWE-835

**Comment by FlorianRappl** [comment]
Sure - consider it done :)

**Comment by sbley** [comment]
With latest pidoc/core 0.18.1 I am getting a type error with flexsearch:
```
ERROR in ./src/codegen/search.codegen
Module build failed (from ../../parcel-codegen-loader/lib/index.js):
TypeError: FlexSearch is not a constructor
    at createSearch (<projectdir>\node_modules\@pidoc\core\src\tools\search.js:8:17)
```

Pinning flexsearch to 0.27.1 (as suggested in other posts) did not help.
https://github.com/nextapps-de/flexsearch/issues/341
